# Supported funding model platforms

github: [MuwMix]
#open_collective: MuwMix 
custom:
  - "https://own.page/muwmix"
  - "https://solscan.io/account/DT3ckdbNuiQMR1mrCpBXCMrhLB19GckVv3YfxsLLiF8z"
