cmake_minimum_required(VERSION 3.22.1)
project("yuma_analysis")
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_library(yuma_analysis SHARED analyzer/audio_analysis.cpp analyzer/tempo_analysis.cpp analyzer/resampler.cpp jni/analysis_jni.cpp)
target_include_directories(yuma_analysis PRIVATE analyzer)
target_compile_options(yuma_analysis PRIVATE -O3 -fvisibility=hidden)
target_link_options(yuma_analysis PRIVATE "-Wl,-z,max-page-size=16384")
find_library(log-lib log)
target_link_libraries(yuma_analysis ${log-lib})
